# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_rc_norm <- function(data, scale_factor) {
    .Call('_scTenifoldNet_lite_matrix_rc_norm', PACKAGE = 'scTenifoldNet.lite', data, scale_factor)
}

